const foods = [
	{
		id: 1,
		category: "breakfast",
		name: "Healthy Meal Plan",
		image: "https://i.ibb.co/Z81qj7H/bannerbackground.png",
		description: "lorem ipsum",
		short_desc: "This is a good food",
		price: 300,
	},
	{
		id: 2,
		category: "breakfast",
		name: "Healthy Meal Plan 2",
		image: "https://i.ibb.co/Z81qj7H/bannerbackground.png",
		description: "lorem ipsum",
		short_desc: "This is a good food",
		price: 300,
	},

	{
		id: 3,
		category: "breakfast",
		name: "Healthy Meal Plan 3",
		image: "https://i.ibb.co/Z81qj7H/bannerbackground.png",
		description: "lorem ipsum",
		short_desc: "This is a good food",
		price: 300,
	},
	{
		id: 4,
		category: "breakfast",
		name: "Healthy Meal Plan 4",
		image: "https://i.ibb.co/Z81qj7H/bannerbackground.png",
		description: "lorem ipsum",
		short_desc: "This is a good food",
		price: 300,
	},
	{
		id: 5,
		category: "breakfast",
		name: "Healthy Meal Plan 5",
		image: "https://i.ibb.co/Z81qj7H/bannerbackground.png",
		description: "lorem ipsum",
		short_desc: "This is a good food",
		price: 300,
	},
	{
		id: 6,
		category: "breakfast",
		name: "Healthy Meal Plan 6",
		image: "https://i.ibb.co/Z81qj7H/bannerbackground.png",
		description: "lorem ipsum",
		short_desc: "This is a good food",
		price: 300,
	},
	{
		id: 7,
		category: "lunch",
		name: "Healthy Meal Plan 7",
		image: "https://i.ibb.co/Z81qj7H/bannerbackground.png",
		description: "lorem ipsum",
		short_desc: "This is a good food",
		price: 300,
	},
	{
		id: 8,
		category: "lunch",
		name: "Healthy Meal Plan 8",
		image: "https://i.ibb.co/Z81qj7H/bannerbackground.png",
		description: "lorem ipsum",
		short_desc: "This is a good food",
		price: 300,
	},
	{
		id: 9,
		category: "lunch",
		name: "Healthy Meal Plan 9",
		image: "https://i.ibb.co/Z81qj7H/bannerbackground.png",
		description: "lorem ipsum",
		short_desc: "This is a good food",
		price: 300,
	},
	{
		id: 10,
		category: "lunch",
		name: "Healthy Meal Plan 10",
		image: "https://i.ibb.co/Z81qj7H/bannerbackground.png",
		description: "lorem ipsum",
		short_desc: "This is a good food",
		price: 300,
	},
	{
		id: 11,
		category: "lunch",
		name: "Healthy Meal Plan 11",
		image: "https://i.ibb.co/Z81qj7H/bannerbackground.png",
		description: "lorem ipsum",
		short_desc: "This is a good food",
		price: 300,
	},
	{
		id: 12,
		category: "lunch",
		name: "Healthy Meal Plan 12",
		image: "https://i.ibb.co/Z81qj7H/bannerbackground.png",
		description: "lorem ipsum",
		short_desc: "This is a good food",
		price: 300,
	},
	{
		id: 13,
		category: "dinner",
		name: "Healthy Meal Plan 13",
		image: "https://i.ibb.co/Z81qj7H/bannerbackground.png",
		description: "lorem ipsum",
		short_desc: "This is a good food",
		price: 300,
	},
	{
		id: 14,
		category: "dinner",
		name: "Healthy Meal Plan 14",
		image: "https://i.ibb.co/Z81qj7H/bannerbackground.png",
		description: "lorem ipsum",
		short_desc: "This is a good food",
		price: 300,
	},
	{
		id: 15,
		category: "dinner",
		name: "Healthy Meal Plan 15",
		image: "https://i.ibb.co/Z81qj7H/bannerbackground.png",
		description: "lorem ipsum",
		short_desc: "This is a good food",
		price: 300,
	},
	{
		id: 16,
		category: "dinner",
		name: "Healthy Meal Plan 16",
		image: "https://i.ibb.co/Z81qj7H/bannerbackground.png",
		description: "lorem ipsum",
		short_desc: "This is a good food",
		price: 300,
	},
	{
		id: 17,
		category: "dinner",
		name: "Healthy Meal Plan 17",
		image: "https://i.ibb.co/Z81qj7H/bannerbackground.png",
		description: "lorem ipsum",
		short_desc: "This is a good food",
		price: 300,
	},
	{
		id: 18,
		category: "dinner",
		name: "Healthy Meal Plan 18",
		image: "https://i.ibb.co/Z81qj7H/bannerbackground.png",
		description: "lorem ipsum",
		short_desc: "This is a good food",
		price: 300,
	},
];

export default foods;
